### ISSUE TITLE
Wouldn't be better to use CSV instead of Markdown?

### ISSUE THREAD

**Issue by jeandersonbc** [samanthakem/tech-conferences-brazil#3]
Nice project!
I think that we could take advantage of the CSV rendering support from Github, though.
Take a look here, for instance: https://help.github.com/articles/rendering-csv-and-tsv-data/

I think it would be easier to search and to maintain the list using CSV.
What do you think?

**Comment by samanthakem** [comment]
Great idea, @jeandersonbc! Let me know if you want to work on this change.

**Comment by samanthakem** [comment]
@jeandersonbc do you know if it is possible to embed a csv file into a markdown file?

**Comment by jeandersonbc** [comment]
I'm not so sure about this but I guess it's not possible. The CSV
visualization is only available when you open the CSV file in the browser.

Still better than formatting a table in markdown (or a list)

But this is just my opinion... I know that usually these "awesome-list"
projects keep everything on the README file.

Anyway, I can help if you agree with this  ¯\_(ツ)_/¯

**Comment by jeandersonbc** [comment]
hmmm.... we can create a link to the CSV file in the README, though. so we
don't have to browser the repository looking for it.

**Comment by samanthakem** [comment]
Yes, I think it is wiser if you add a link to the csv file, it is nice to have both options of looking through the README.md file and the csv file. I will try to keep visible the events on README.md with range of 2 years from now, the others one will be archived on the CSV. If you want to start working on the CSV file, do it.

**Comment by jeandersonbc** [comment]
sounds good to me ;) I liked the idea of keeping the latest in confs on the
README.

I will provide a PR soon

Jeanderson Candido

Graduate student in Computer Science
Federal University of Pernambuco - Brazil
http://jeandersonbc.github.io

2017-08-31 10:17 GMT-03:00 Samantha Monteiro <notifications@github.com>:

**Comment by jeandersonbc** [comment]
Change merged. Closing issue.
